spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:~/todos
    driverClassName: org.h2.Driver
    username: todos
    password: todos
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
